extends: sysu_resize.yaml

config_select: configs/stage_a/person_assets/sysu_person_fit.yaml
prepared_data_root: /home/lab929/ybj/datasets/person-assets-512x256/person_fit
experiment_name: person_assets_sysu_person_fit
metric_experiment_id: PERSON-ASSETS-SYSU-PERSON-FIT
output_root: train_outputs/person_assets_sysu/person_fit
metric_events_path: train_outputs/person_assets_sysu/person_fit/events.jsonl
