extends: base_pmt_mbpatch_sr.yaml

data:
  height: 512
  width: 256
  sr_modalities: [rgb, ir]

experiment:
  id: PMSR-A3-swinir-both-x2
  purpose: measure the incremental effect and risk of IR SwinIR

output:
  root: /home/cgv841/ybj/SALT-VI/outputs/super_resolution/PMSR-A3-swinir-both-x2
