output_path: train_outputs/stage_a_vision_text_encoder/
CUDA_VISIBLE_DEVICES: "0"
gpu_id: "0"
pretrain_choice: PMT_VIT
pmt_pretrained: /home/cgv841/ybj/SALT-VI/pretrained/pmt_sysu/jx_vit_base_p16_224-80ecf9dd.pth
pmt_embed_dim: 768
pmt_patch_size:
- 16
- 16
pmt_stride_size:
- 12
- 12
pmt_depth: 12
pmt_num_heads: 12
pmt_mlp_ratio: 4.0
pmt_dropout: 0.03
pmt_attention_dropout: 0.0
pmt_drop_path_rate: 0.1

training_mode: RGB_IR
joint_mode: image_only
loss_names: wrt,id
llm_aug: false
Feat_Filter: false
Fix_Visual: false
freeze_text_in_image_only: true

test_model_type: IR
test_modality: IR
fusion_way: add
pooling: GEM
prj_output_dim: 2048

dataset: sysu
sysu_data_path: /home/cgv841/datasets/SYSU-MM01/
img_h: 288
img_w: 144
img_size:
- 288
- 144
batch_size: 32
num_pos: 4
seed: 1
total_train_epoch: 40
eval_start_epoch: 20
eval_epoch: 2
